on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20.0.0'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.GIT_CPANEL_SERVER }} # Your FTP server
        username: ${{ secrets.GIT_CPANEL_USER }} # Your FTP username
        password: ${{ secrets.GIT_CPANEL_PWD }} # Referencing the FTP password stored as a secret
        protocol: ${{ secrets.GIT_CPANEL_PROTOCOL }}
        port: ${{ secrets.GIT_CPANEL_PORT }} # FTP port
        local-dir: ./ # Local directory to deploy (adjust if necessary)
        server-dir: /heelheidbusiness/ # Adjust based on your server
  
